#!/bin/bash
# Shared version defaults. Distribution settings apply only to release targets.

FRITZ_VERSION="${FRITZ_VERSION:-$(awk -F '"' '/^version = / { print $2; exit }' Cargo.toml)}"
FRITZ_BUILD_NUMBER="${FRITZ_BUILD_NUMBER:-$(awk '/^[[:space:]]*CURRENT_PROJECT_VERSION:/ { print $2; exit }' app/project.yml)}"
export FRITZ_VERSION FRITZ_BUILD_NUMBER

if [[ "${FRITZ_DISTRIBUTION:-0}" == 1 ]]; then
  FRITZ_RELEASE_BASE_URL="${FRITZ_RELEASE_BASE_URL:-https://fritz.rel.me}"
  FRITZ_CODE_SIGN_IDENTITY="${FRITZ_CODE_SIGN_IDENTITY:-Developer ID Application: Gabriel Handford (U2622K69A6)}"
  FRITZ_SPARKLE_FEED_URL="${FRITZ_SPARKLE_FEED_URL:-$FRITZ_RELEASE_BASE_URL/appcast.xml}"
  FRITZ_SPARKLE_PUBLIC_ED_KEY="${FRITZ_SPARKLE_PUBLIC_ED_KEY:-zPiF+/oTWNOkR4pu0JwQBE+kY2koW5DsSiP+gTeDESs=}"
  FRITZ_UPDATE_DOWNLOAD_URL_PREFIX="${FRITZ_UPDATE_DOWNLOAD_URL_PREFIX:-$FRITZ_RELEASE_BASE_URL/updates}"
  FRITZ_HOMEPAGE_URL="${FRITZ_HOMEPAGE_URL:-$FRITZ_RELEASE_BASE_URL}"
  FRITZ_NOTARY_PROFILE="${FRITZ_NOTARY_PROFILE:-REL}"
  FRITZ_SPARKLE_KEY_ACCOUNT="${FRITZ_SPARKLE_KEY_ACCOUNT:-fritz}"
  export FRITZ_RELEASE_BASE_URL FRITZ_CODE_SIGN_IDENTITY FRITZ_SPARKLE_FEED_URL
  export FRITZ_SPARKLE_PUBLIC_ED_KEY FRITZ_UPDATE_DOWNLOAD_URL_PREFIX
  export FRITZ_HOMEPAGE_URL FRITZ_NOTARY_PROFILE FRITZ_SPARKLE_KEY_ACCOUNT
fi
